### ISSUE TITLE
Hi. I would like to know when Swift will be able on Codewars? :horse:

### ISSUE THREAD

**Issue by khuong291** [Codewars/codewars-runner-cli#134]

**Comment by jhoffner** [comment]
It will be available soon after someone contributes a complete integration to this project. Are you interested in taking on the task?

**Comment by joaopaulogalvao** [comment]
@jhoffner Hello Jake, I would be interested in that, also if @khuong291 is up for teaming up, he could count on me. But before I jump into it, could you let me know what set of skills(other then Swift) are required? So I can let you know if I can help with it. If you could provide some examples on how to do that, maybe I can get it running. This would be my first big project open source contribution, and with some help I may understand the starting point. I'm totally up for helping.

**Comment by khuong291** [comment]
Yes, will someone work together with me?

**Comment by joaopaulogalvao** [comment]
@khuong291 Great. Just added. I am looking forward to hearing from @jhoffner and we can go from there. It will be great to help with this.

**Comment by jasondebolt** [comment]
I would be interested in helping out with this. I've been wanting this integration for a long time. 

Codewars is by far the best interactive code challenge platform in the world, and Swift should be a supported language. 

Jhoffner@, can you point me to the integration documentation?

**Comment by jhoffner** [comment]
Great to hear. Yes the readme of this repo should get you started.

**Comment by jasondebolt** [comment]
I've looked through all of the code in codewars-runner-cli and found several pre-existing Swift and OSX files. What were some of the challenges on this Swift integration? Should I continue going the XCode route or should I try to get a Swift docker image running?

**Comment by jhoffner** [comment]
Thats some code that was left over from before Swift was Linux compatible. It was meant to be ran on OSX, but of course we couldn't run it on our servers. It may be in working shape to get you started, or you may want to just start from scratch, I'm not really sure.

**Comment by jasondebolt** [comment]
Quick update on the Swift integration. I've successfully build a swift image from the base codewars image and have basic code evaluation working (see output below). I still need to update the Makefile and create a swift.docker file. My current swift image is an isolated image under my own username (jasondebolt/swift-runner). What steps are required to push a swift image to the codewars docker hub?

===============
  swift runner
    .run
42
      ✓ should handle basic code evaluation (79ms)
      example challenges
        ✓ should define an initial code block
        ✓ should have a passing algorithms example (74ms)
        ✓ should define an initial code block
        ✓ should have a passing bug fixes example
        ✓ should define an initial code block
        ✓ should have a passing refactoring example (73ms)
        ✓ should define an initial code block
        ✓ should have a passing reference example (78ms)


  9 passing (353ms)

 ---> 41a1bb2fbe64
Removing intermediate container 096d2c0e4e1b
Step 18 : ENTRYPOINT timeout 15 node
 ---> Running in 2ee627152547
 ---> afdb1c313b22
Removing intermediate container 2ee627152547
Successfully built afdb1c313b22
===============

**Comment by jasondebolt** [comment]
Hi Jake,

I've finished steps 1-5 of "How to add a new language" in the Codewars CLI Github repo for Swift. I've got it working with CW2 (maybe I can implement XCTest at some point), and all tests are passing when I build the image.

One concern I have is that I'm inlining the CW2 assertion code as a string in the lib/runners/swift file. I'll try to add a snippets.swift.addSwiftFramework rule like you did with Python.

Do you have a preference for Git commits? This is not a lot of code, so let me know if you are OK with me sending you this early Swift integration in a single commit.

**Comment by jhoffner** [comment]
Hi @jasondebolt. Thanks for contributing. To answer your questions
> What steps are required to push a swift image to the codewars docker hub? 

No steps are needed. You add the docker file to docker folder within the repo and submit a PR. Once it is merged I will integrate it into CW and docker hub. 

> I'll try to add a snippets.swift.addSwiftFramework rule like you did with Python

No need. Python is the last remaining snippet that needs to be moved out of that file. Inline is better (using javascript template strings is recommended). 

> Do you have a preference for Git commits?

However many commits you need. No need to squash.

> Maybe I can implement XCTest at some point

Official test frameworks are preferred, CW-2 is a carry over from Codewar's less refined early days - back when we didn't use Docker and had to use hacky sandboxes. You can submit what you have though I would love to take a look. Often times a CW-2 framework offers a much simpler and easy to use API so its not bad to have both options available.

**Comment by jasondebolt** [comment]
Hi Jake,

I am able to run XCTest test cases on the swift image, but I'm wondering what you would prefer the XCTest result stdout to look like (see test output below). Does this output need to be transformed to use the <DESCRIBE::>, <PASSED::>, etc. format or should be leave it as is? If it needs to be transformed, should we transform with nodejs (using sanitizeStdOut)? I can't find a simple way to modify the stdout using Swift.

Test Suite 'All tests' started at 18:08:38.557
Test Suite 'bin.xctest' started at 18:08:38.558
Test Suite 'CalculatorTests' started at 18:08:38.558
Test Case 'CalculatorTests.testAddCheck' started at 18:08:38.558
Test Case 'CalculatorTests.testAddCheck' passed (0.0 seconds).
Test Case 'CalculatorTests.testSubCheck' started at 18:08:38.558
Test Case 'CalculatorTests.testSubCheck' passed (0.0 seconds).
Test Case 'CalculatorTests.testMulCheck' started at 18:08:38.558
calculator.swift:35: error: CalculatorTests.testMulCheck : XCTAssertEqual failed: ("0") is not equal to ("20") - calc.mul(4, 5) should be 20
Test Case 'CalculatorTests.testMulCheck' failed (0.0 seconds).
Test Suite 'CalculatorTests' failed at 18:08:38.558
         Executed 3 tests, with 1 failure (0 unexpected) in 0.0 (0.0) seconds
Test Suite 'bin.xctest' failed at 18:08:38.558
         Executed 3 tests, with 1 failure (0 unexpected) in 0.0 (0.0) seconds
Test Suite 'All tests' failed at 18:08:38.558
         Executed 3 tests, with 1 failure (0 unexpected) in 0.0 (0.0) seconds

**Comment by jhoffner** [comment]
There are two approaches. Ideally we find a way to tie into the test framework. Many often support custom outputers/formatters. Sometimes if there is another popular test framework out there that is more flexible, we will choose that, even if its not the most commonly used framework. For example igloo was used for C++. 

It looks like Swift has another framework called [Quick/Nimble](https://github.com/Quick/Quick) which seems to be pretty popular. Doing a quick check it doesn't seem like either XCTest or Quick make it easy to customize the output. It might be possible to override some of the classes perhaps (I'm not too sure if thats possible in Swift). You could maybe fork a project and just change the code directly, but that might get messy if there are a lot of files to have to compile. Thats definitely not the ideal solution. If you can compile the binaries and just include those then it might not be that bad though - this is what I had to do for the C# NUnit implementation. 

As a last resort, you can just transform the output. This is the least ideal though because it can be buggy and sometimes difficult to handle things as cleanly as they could be. The Rust implementation was done this way so if thats the best we can do then you can use the Rust code as an example. 

As far as what the output should look like, here is an example of how I would transform the output you gave:

~~Test Suite 'All tests' started at 18:08:38.557~~
~~Test Suite 'bin.xctest' started at 18:08:38.558~~
~~Test Suite 'CalculatorTests' started at 18:08:38.558~~`<DESCRIBE::>CalculatorTests`
~~Test Case 'CalculatorTests.testAddCheck' started at 18:08:38.558~~`<IT::>testAddCheck`
~~Test Case 'CalculatorTests.testAddCheck' passed (0.0 seconds).~~`<PASSED::>Test Passed`
`<COMPLETEDIN::>0`
~~Test Case 'CalculatorTests.testSubCheck' started at 18:08:38.558~~`<IT::>testSubCheck`
~~Test Case 'CalculatorTests.testSubCheck' passed (0.0 seconds).~~`<PASSED::>Test Passed`
`<COMPLETEDIN::>0`
~~Test Case 'CalculatorTests.testMulCheck' started at 18:08:38.558~~`<IT::>testMulCheck`
`<ERROR::>calculator.swift:35: error: CalculatorTests.testMulCheck : XCTAssertEqual failed: ("0") is not equal to ("20") - calc.mul(4, 5) should be 20`
~~Test Case 'CalculatorTests.testMulCheck' failed (0.0 seconds).~~`<COMPLETEDIN::>0`
~~Test Suite 'CalculatorTests' failed at 18:08:38.558~~`<COMPLETEDIN::>1`

~~Executed 3 tests, with 1 failure (0 unexpected) in 0.0 (0.0) seconds
Test Suite 'bin.xctest' failed at 18:08:38.558
Executed 3 tests, with 1 failure (0 unexpected) in 0.0 (0.0) seconds
Test Suite 'All tests' failed at 18:08:38.558
Executed 3 tests, with 1 failure (0 unexpected) in 0.0 (0.0) seconds~~

**Comment by jhoffner** [comment]
Also just found this [article](https://www.objc.io/issues/15-testing/behavior-driven-development/). Apparently these frameworks all integrate into XCTest. It also looks like [Sleipnir](https://github.com/railsware/Sleipnir) supports custom formatters so that might be your best bet.

**Comment by jasondebolt** [comment]
Hi Jake,

Quick update on the Swift integration. I was able to modify XCTest standard output to match the Codewars spec. I've also built a docker image from the codewars base image which downloads dependencies, Swift source, modifies some Swift XCTest code, loads a presets.ini file, and compiles everything. I can run the container and run "$ swift calculator.swift" and produce the test output below. I still need to make the necessary changes such as removing the first two <DESCRIBE::> tags, try to remove the class names from the <IT::> tags, and change the <COMPLETEDIN::> times.

Just to confirm, should the time in <COMPLETEDIN::> return the test duration in milliseconds in string format?

<DESCRIBE::>All tests
<DESCRIBE::>bin.xctest
<DESCRIBE::>CalculatorTests
<IT::>CalculatorTests.testAddCheck
<PASSED::>Test Passed
<COMPLETEDIN::>2.59876251220703e-08
<IT::>CalculatorTests.testSubCheck
<ERROR::>CalculatorTests.testSubCheck : XCTAssertEqual failed: ("-51") is not equal to ("-1") - calc.sub(3, 4) should be -1
<FAILED::>CalculatorTests.testSubCheck
<COMPLETEDIN::>1.24990940093994e-07
<IT::>CalculatorTests.testMulCheck
<PASSED::>Test Passed
<COMPLETEDIN::>1.8000602722168e-08

**Comment by jasondebolt** [comment]
Just created a pull request:

https://github.com/Codewars/codewars-runner-cli/pull/239

**Comment by jasondebolt** [comment]
Hi Jake,

Have you seen this yet? AWS Firecracker is a service for launching micro
VMs.

https://aws.amazon.com/blogs/aws/firecracker-lightweight-virtualization-for-serverless-computing/

Seems like It could potentially save you guys a lot of money.

Jason
