### ISSUE TITLE
Elixir runner evaluates initial solution too

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#153]
hence provides some ugly warnings ablut variables undeclared or unused, those warnings block the kata to pass even if all tests are passed.
Please refer to [this kumite](http://www.codewars.com/kumite/56bb7b7838dd34e7b200180c?sel=573f81cc94a88be792000082)

**Comment by jhoffner** [comment]
"Preloaded Code" is not the initial solution, its additional code that is ran before the solution. Used in Kata when you need to have additional code run before the user's in order to set up the context. Its used in Kumite when you need to have setup code thats required to run your code, but is not the focal point of what you are trying to demonstrate. 

Essentially the runner just concatenates the preloaded code with the solution code before running it.

**Comment by javatlacati** [comment]
my bad :)
