### ISSUE TITLE
New language translations don't pass trough beta process

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#181]
When a new language is addeded can you make the kata beta again so if translation goes bad as in [this case](http://www.codewars.com/kata/56069d0c4af7f633910000d3/discuss/csharp) one could easily fix it and get improved by the comunity.

**Comment by jhoffner** [comment]
This is the wrong place to post this as it is related to CW and not the runner specifically. However I'm going to close it anyway since updating the beta process is far too much re-work to be able to be considered right now. At the most I think there could be a process where translations must be voted as ready by multiple people - but that requires a number of things to make work as well so it would also not be something that we could get too quickly.
