### ISSUE TITLE
PHP pass on any error

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#232]
if test case has error code will pass

**Comment by OverZealous** [comment]
Can you give me an example? I have a (code runner) test case in place to handle when a test has a PHP error or an exception is thrown specifically to capture this scenario. In both cases, the output only contains `<FAILED::>`, and no `<PASSED::>` results.

**Comment by javatlacati** [comment]
https://www.codewars.com/kata/sum-of-numbers-from-0-to-n/solutions/php random tests pass always :cry:

**Comment by OverZealous** [comment]
I'm still not sure what the issue is. The code I'm seeing there will always pass.

```php
      if($totest === $rndF){
        $this->assertEquals($totest,$rndF);
      }
      else{
        $this->assertNotEquals($totest,$rndF);
      }
```

This cannot fail. If the values are equal, then they are tested to be equal.

- If I swap the tests, it fails _exactly_ as expected.
- If I throw an error, either within the code, or within the test, _or_ have a syntax error, it fails, as expected.
