### ISSUE TITLE
Getting host error when trying to create Swift kata

### ISSUE THREAD

**Issue by jasondebolt** [Codewars/codewars-runner-cli#243]
I see that Swift is now listed as a language on Codewars. That's great!

I did notice that I am getting some errors when trying to create Swift kata (see attached screenshots). You're probably already aware of this, but I thought I should file a bug to track it.

Steps to reproduce:
1) Attempt to translate an existing Kata (multiply, hello world, etc.) to Swift
2) Enter some test asserts using either cw-2 or XCTest.
3) Click "Run" to run the tests
4) In the output on the left, you will see that we get a runner.codewars.io Host error.

<img width="497" alt="screen shot 2016-09-26 at 10 09 32 am" src="https://cloud.githubusercontent.com/assets/1709984/18844437/174fada8-83d2-11e6-91e8-09f4b773b7f7.png">
<img width="490" alt="screen shot 2016-09-26 at 10 09 38 am" src="https://cloud.githubusercontent.com/assets/1709984/18844436/174dd6e0-83d2-11e6-87ac-32890ca226e5.png">

**Comment by jhoffner** [comment]
Yeah thats odd thats up there, I'll do another deployment. Swift still isn't ready to go and shouldn't be enabled yet. I've tried to build it a few times and it keeps timing out. I was hoping that if the image size really does shrink (I'm suspect because Docker stores each `RUN` command in its own layer, so it may still require a large download) then I can fit it on the current servers even without fixing having to fix the Thin Pool issue first.
