### ISSUE TITLE
Django Project Template

### ISSUE THREAD

**Issue by saady** [codewars/codewars-runner-cli#344]
Currently I'm doing this:

```
docker run codewars/python-runner run -l python  -c 'from django.db import models
# Create your models here
class Article(models.Model):
   headline = models.CharField(max_length=255)
   publish_date = models.DateTimeField()
   content = models.TextField()'
```

```
Traceback:
   in <module>
   in Article
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 1072, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 166, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

```
Any help would be highly appreciated.

Thank you.

**Comment by kazk** [comment]
I know nothing about Django, but don't you need a specific project structure?

From [Writing your first Django app, part 1](https://docs.djangoproject.com/en/1.10/intro/tutorial01/):

```
# django-admin startproject mysite

mysite/
    manage.py
    mysite/
        __init__.py
        settings.py
        urls.py
        wsgi.py
```

Here's what I found by googling the error message.

> You can't just fire up Python and check things, Django doesn't know what project you want to work on. You have to do one of these things:
> - Use `python manage.py shell`
> - Use `django-admin.py shell --settings=mysite.settings` (or whatever settings module you use)
> - Set `DJANGO_SETTINGS_MODULE` environment variable in your OS to `mysite.settings`
> - (This is removed in Django 1.6) Use `setup_environ` in the python interpreter:
> ```python
> from django.core.management import setup_environ
> from mysite import settings
>
> setup_environ(settings)
> ```
> Naturally, the first way is the easiest.
> http://stackoverflow.com/a/15556596

---

What is your goal?
If you're simply trying to run Django app in docker, then I think the official [python image](https://hub.docker.com/_/python/) is [the recommended way](https://hub.docker.com/_/django/).

```dockerfile
FROM python:3.4

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . .

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
```

**Comment by saady** [comment]
@kazk Thank you for your help, I really appreciate the tremendous effort you did in order to explain things.
What I mean is that How can I do it using codewars python-runner using test strategy..I'm completely agree that I need a project structure.

in python-runner we can do:
```
docker run codewars/python-runner run -l python  -c 'x=lambda a: a * a' -f 'test.expect(x(4) == 16)'
```

I wonder if we can do that for django.

Thank you.

**Comment by jhoffner** [comment]
I'm out of the office until tomorrow so I can provide more details then, but if you want to support more files in order to support the core project structure needed to run a project, it's possible to save those files as a gist or GitHub repo and then download those files into the working directory on each run. You would still need to find a way to boot the application. 

I also know it's possible to support rails using only the preloaded/setup code block, so Django may also be possible. I can provide examples of that tomorrow.

**Comment by saady** [comment]
@jhoffner Thank you, this is will be highly appreciated.

**Comment by jhoffner** [comment]
For documentation on downloading files into the runner via Github/Gist, you can go [here](https://github.com/Codewars/codewars-runner-cli/blob/master/documentation/setup_config_statements.md)

I created a [Kumite](https://www.codewars.com/kumite/58dd33960f263eafce00002e?sel=58dd33960f263eafce00002e) to demonstrate how you could test a Rails controller.

**Comment by jhoffner** [comment]
I'm going to leave this issue open for now as a reminder that this can and should be officially documented. Ideally I would like to showcase kumite on Codewars to help document these things.

**Comment by kazk** [comment]
@jhoffner how can I turn off the colors for verbose logging? I see all the control characters.

![image](https://cloud.githubusercontent.com/assets/639336/24516147/89fbea90-152e-11e7-9915-343645823d39.png)

I found this, but I don't know where to put it.

> ```ruby
> config.colorize_logging = false
> ```
> http://stackoverflow.com/a/14237478

Also, what is the version? I couldn't tell from ruby.docker.

**Comment by kazk** [comment]
I figured it out :)

```ruby
ActiveSupport::LogSubscriber.colorize_logging = false
```

![image](https://cloud.githubusercontent.com/assets/639336/24517438/2ceb609c-1533-11e7-9166-cb8a37aff301.png)

**Comment by kazk** [comment]
For Django, I found some possibility to test in similar way, but we probably need to improve Python's tests first and support running tests using `python -m unittest discover -s opts.dir`.

> When it comes to mocking in Django, I reccomend the [mock](https://pypi.python.org/pypi/mock/) library. Another advantage, besides faster tests, of using mocking instead of Django's default testing behavior is that you don't need django to setup the database to run your tests, and you can subclass unittest's [TestCase](https://docs.python.org/2/library/unittest.html#unittest.TestCase) instead of django [TestCase](https://docs.djangoproject.com/en/dev/topics/testing/overview/#django.test.TestCase) (which saves you the database cleanup between tests). With the examples provided here I can run these with `manage.py test django_testing` or with `python -m unittest discover -s django_testing` (using Python2.7).
> <http://www.mattjmorrison.com/2011/09/mocking-django.html>

Also, it might not work exactly as described since the blog post is old.

`mock` library is builtin `unittest.mock` in Python 3.

**Comment by jhoffner** [comment]
Using discover would be a big improvement. I'm not sure if it has a performance penalty but if it does we could also add the command and args as a config/options value so that it can be overridden using a setup config statement.

I.E:
```python
# @config cmd python
# @config cmdArgs -m unittest discover -s opts.dir
```

However unfortunately Codewars Kata doesn't support unittest yet (only Kumite). I haven't bothered to update the interface yet to support multiple frameworks since its a disaster of a codebase and I'm working on a full rewrite that will replace the kata editor/trainer.

**Comment by kazk** [comment]
I'll look into `unittest` and make a proof of concept from scratch. If everything goes well, and if you like it, I'll try porting that back to `codewars/python-runner`.

Why was `cw-2.py` created? `unittest` seems to have everything we need and `unittestwrapper.py` was also created in the same month (2014-06) :confused:

---

> I'm working on a full rewrite that will replace the kata editor/trainer.

I'm looking forward to this. Are you using vuejs? (I noticed you opened an issue on your profile).

**Comment by jhoffner** [comment]
> Why was cw-2.py created?
If I recall correctly, Python was the first language we added after the initial 3 (JS, Coffee, Ruby). We added unittest support but at the time it felt like unittest was just overly verbose and having cw-2 made it a lot easier to translate kata (which I had to do myself back then) - plus it kept things consistent. Then I guess at some point when more languages started to get added it was decided that recreating cw-2 over and over again made little sense. 

> Are you using vuejs?
Yes, and it's amazing. I literally wouldn't change a thing about the framework - it's perfect. Vuex on the other hand, it's good but it doesn't feel perfect.

**Comment by kazk** [comment]
> having cw-2 made it a lot easier to translate kata (which I had to do myself back then) - plus it kept things consistent.

Makes sense now, thanks.

I'm really happy that you're using Vue.js because I've been wanting to try. I had Vue.js, [Riot.js](http://riotjs.com/) and [Mithril](https://mithril.js.org/) bookmarked. I've read many positive reviews and their documentations are great. Now I have a good reason to start learning :)

**Comment by jhoffner** [comment]
The Coderunner results UI is built in Riot.js. The codebase quickly got out of hand and I decided to rebuild it as a side project, with Vue.js, for the sake of learning it. That quickly turned into me adding code editor support and then it started to go from a little side project to a full IDE type of thing that we now hope to use for both Qualified and Codewars. 

Riot is ok. Its more of a utility library. They came out with version 3 after I had built it, probably some of the buggy stuff has been fixed - but Vue really isn't much bigger and its far better to work with. After a few hours of building an app using reactive properties in Vue you will see why its superior to Riot. Vue's reactive nature takes away maybe 50% or more of the complexity that you normally have to deal with in a front-end app, and there is something magical about its design that keep me in check with writing good clean code. Its also dead simple to learn. In a few hours you will pretty much know everything you need to know about it - except for vuex/flux. I'm still getting used to its paradigm and experimenting with what makes the most sense, best practices, etc - as I encounter new challenges of building out a complex app.

**Comment by kazk** [comment]
@jhoffner I started to learn Vue.js after reading your comment :) I've finished reading the "Essentials" section of the "Guide" except for the "Components" and I'm hooked.

I wanted to make something to continue learning and thought extended leaderboard using data pulled from the API might be interesting. So I started to look into what's available and found that `/users/:user/code-challenges/completed` endpoint chokes for users with more than ~1.2k challenges completed. Is this known issue? If not, where should I report?

The following request returns HTML with `5xx: Server Error` with usual `This doesn't happen often, but it looks like something is broken. Hitting the back button and trying again might be your best bet.`.
```
curl 'https://www.codewars.com/api/v1/users/kazk/code-challenges/completed'
```

**Comment by jhoffner** [comment]
Great! Glad you are checking it out its an awesome framework. Def read the components section and I would recommend using their built in project scaffold that sets everything up to work with .vue files. 

The API isn't maintained very well, since its not used that often AFAIK. I didn't realize that was choking so I can take a look. Now that the pre-calculated stats exist I should be able to make that endpoint much faster.

**Comment by kazk** [comment]
I stopped reading because it said, "Components are one of the most powerful features of Vue." and I thought I should play with basic features before reading. The documentation was so good that it made me feel like I know Vue.js already, but I know I don't. I'll also take a look at `vue-cli`, thanks :)

> The API isn't maintained very well, since its not used that often AFAIK.

Is there undocumented endpoints? If so, I can add them to `codewars-api-docs` whenever I find the time. Is `dev.codewars.com` hosted on GitHub pages? I noticed that some fixes merged in `codewars-api-docs` are not applied yet. Also the data returned looks completely different now. I can work on this too.

> I didn't realize that was choking so I can take a look. Now that the pre-calculated stats exist I should be able to make that endpoint much faster.

Thanks :)

---

> Also cool idea to extend the leaderboard!

I was thinking to add some leaderboards not based on honor. Here're some ideas I got after looking at data from `/users/:user` of top 50 users on "Completed Kata" leaderboard:

- `ranks.overall.score`
  - makes me the 1st :smirk: (by little bit)
- `ranks.languages.{language}.score` for popular languages
  - shows experts in that language
  - most in top 50 were polyglots, found 1 user who did only Python
- sum of `ranks.languages.{language}.score`
  - polyglots who solves the same kata in multiple languages
  - makes me the 1st :smirk:
- `codeChallenges.totalCompleted`
  - `4096`!
- `codeChallenges.totalAuthored`
  - `682`!
- number of approved translations
  - I couldn't find a way to get this

**Comment by kazk** [comment]
Closing because it's not really possible to add support on Codewars because it only supports simple challenges with solution and tests.

Qualified does support Django so maybe in the future.
