### ISSUE TITLE
JavaScript CW-2 Test.assert(Not)Contains should be documented

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#368]
Ik that the Test Reference in the Docs on Codewars haven't been updated since eons, but I think methods such as `Test.assertContains` and `Test.assertNotContains` should at least be made aware to Codewars users so they know how to use them when necessary.  I literally *just* discovered these two test methods by reading the code for the CW-2 testing framework itself (I was actually searching for something different) but it seems that they are currently just sitting there in the CW-2 framework with no purpose as I haven't seen them used even **once** in a JS Kata so far.

**Comment by kazk** [comment]
- Add `Test.assert(Not){DeepEquals,Contains}`

<dl>
  <dt>Test.assertDeepEquals(actual, expected, msg)</dt>
  <dd>
    Checks that the actual value equals the expected value by performing deep comparison. Unlike <code>Test.assertSimilar</code>, values are not turned into strings.<br>
    A useful message will be displayed for both pass and fail outcomes.
    The msg argument is optional. If given it will be displayed in addition to the typical message used.
  </dd>

  <dt>Test.assertNotDeepEquals(actual, unexpected, msg)</dt>
  <dd>
    Checks that the actual value does not equal the unexpected value by performing deep comparison. Unlike <code>Test.assertSimilar</code>, values are not turned into strings.<br>
    A useful message will be displayed for both pass and fail outcomes.
    The msg argument is optional. If given it will be displayed in addition to the typical message used.
  </dd>

  <dt>Test.assertContains(actual, expected, msg)</dt>
  <dd>
    Checks that the actual value contains the expected element.<br>
    A useful message will be displayed for both pass and fail outcomes.
    The msg argument is optional. If given it will be displayed in addition to the typical message used.
  </dd>

  <dt>Test.assertNotContains(actual, unexpected, msg)</dt>
  <dd>
    Checks that the actual value does not contain the unexpected element. <br>
    A useful message will be displayed for both pass and fail outcomes.
    The msg argument is optional. If given it will be displayed in addition to the typical message used.
  </dd>
</dl>

---

- Remove `Test.callCount(methodName)`
- Update `Test.inspect(object)` because JSON representation is misleading
  > Returns a string representation of the object. For simple objects toString() will be used, for complex objects a JSON representation will be given.
  
  Returns a string representation of the object using `util.inspect`.
  (Arrays are formatted differently, but I'm not sure how to word it)

**Comment by kazk** [comment]
This will be included in Codewars/codewars.com#881.

**Comment by kazk** [comment]
Added to Wiki.
