### ISSUE TITLE
Node v8 Support

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#432]
Now that Node 8 is released, we should add support for it to the runner.

**Comment by Voileexperiments** [comment]
Looks like CW has just got new Node versions (v6.6.0 -> v6.11.0, and brand new v8.1.3).

**Comment by Voileexperiments** [comment]
https://www.codewars.com/kata/5967e5d5c6427d73cf000052/discuss#59688526b55cd14232000068

Apparently the version update is causing some different behaviour from before (this kata tries to generate an array of size `Number.MAX_SAFE_INTEGER - 1` for the last random test).

**Comment by kazk** [comment]
I'm pretty sure that's going to use up a lot of memory. The error message is basically saying that.
Did it use to work before?

If multiple containers are running on the single instance of `t2.micro`, the added languages might have caused less memory allowed?

**Comment by Voileexperiments** [comment]
Yes, it used to work before, which is why there are working solutions.

(They've been all invalidated after a re-publish, of course.)

**Comment by kazk** [comment]
I guess I misread those comments. I thought the author added that after some people had passed so I wanted to make sure that the Node version is the issue.

If it currently works using Node v6.x and doesn't in v8.x, then there're some compatibility issue. The kata shouldn't be available in the version that doesn't work. Some JavaScript kata doesn't allow one to select certain versions of Node. I don't know how the version availability is decided though.

If it doesn't work in any versions of Node anymore, then some condition might have changed like amount of available memory. This might be due to newly added images or the new Java image using more memory. I still don't know exactly how these containers are operated, but a container might use up as much as it needs if the memory restrictions are not specified.
