### ISSUE TITLE
Array#delete_if and Array#reject are grouped together and incorrectly treated as equivalent methods in Ruby solutions

### ISSUE THREAD

**Issue by njohnson7** [Codewars/codewars-runner-cli#436]
`Array#delete_if` mutates the array, while `Array#reject` returns a new array, so these methods should not be treated as equivalent.

Here is an example:
![image](https://user-images.githubusercontent.com/18152802/27044468-85bebf4e-4f52-11e7-8265-37577ce8d6a3.png)
https://www.codewars.com/kata/reviews/521d8d1a123ebb5a8900008d/groups/5381907ea289d5181e000547

Here are the relevant docs pages: 
- https://devdocs.io/ruby~2.4/array#method-i-delete_if
- https://devdocs.io/ruby~2.4/array#method-i-reject

**Comment by kazk** [comment]
@njohnson7 thanks for reporting :)

@jhoffner this is [Codewars/code-grouper](https://github.com/Codewars/code-grouper)'s issue, right? Can you move this there?

[code-grouper/lib/code_grouper.rb#L146-L147](https://github.com/Codewars/code-grouper/blob/da95b5ba1a6e4720822d13cf12a0ada613528982/lib/code_grouper.rb#L146-L147)
![image](https://user-images.githubusercontent.com/639336/27055622-df3a90b2-4f79-11e7-8e3b-91b0724dcf19.png)

Same issue with `keep_if` and `select`.
`delete_if` and `reject!` is not the same thing either because `reject!` can return `nil` when nothing changed.

**Comment by jhoffner** [comment]
Issue moved to [Codewars/code-grouper #4](https://github.com/Codewars/code-grouper/issues/4) via [**ZenHub**](https://www.zenhub.com/)
