### ISSUE TITLE
Docker images end up being changed on every repo change

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#471]
Because of how we are packing most of the images right now, if just about anything changes in the repo, it means we end up changing the images on next build. This results in new images being pushed and then having to be pulled by servers later. 

We should minimize which changes can affect an image by specifically adding the files that are relevant to each image. `java.docker` is currently setup this way. This would improve our deployment processes greatly.

**Comment by kazk** [comment]
@jhoffner 

I noticed that cache from pulled image gets invalidated on
```dockerfile
COPY package.json /tmp/package.json
```
`java-runner` is still rebuilt on Travis for unrelated changes because of this.
I think the first `ADD/COPY` in Dockerfile triggers invalidation, but I haven't confirmed.
I've been looking into why this is happening before I get started on removing `ADD . /runner`.

How are you building the image pushed to Docker Hub?
I see many files in `.dockerignore` that doesn't exist in this repository, maybe you have some other files that's affecting build context?
Can you check for any untracked files not in `.dockerignore`? Top level directories looked the same, but I haven't checked deeper.

**Comment by jhoffner** [comment]
> How are you building the image pushed to Docker Hub?

On a Jenkins server. The make file is used (`make java`)

> I see many files in .dockerignore that doesn't exist in this repository, maybe you have some other files that's affecting build context?
These are mostly added because during development we use docker compose which maps volumes back to the host machine. Those volumes then end up having files added through running the container itself. We want to prevent any container runtime created files from actually being baked into the image later. Shouldn't be an issue at all on Jenkins since it isn't using volumes.
