### ISSUE TITLE
Add Elm support

### ISSUE THREAD

**Issue by HairyRabbit** [Codewars/codewars-runner-cli#520]
Support for [elm-lang](http://elm-lang.org/)? like ts or coffee.

And the test library, [elm-test](https://github.com/elm-community/elm-test).

**Comment by kazk** [comment]
Just an update. I've experimented with `elm-test` (with [node-test-runner](https://github.com/rtfeldman/node-test-runner)).
I'm pretty sure it's possible to produce Codewars output from JSON produced with `--report=json` option. The problem is that `elm-test` [ignores anything printed to stdout when the reporter is `json` or `junit`](https://github.com/rtfeldman/node-test-runner/blob/4f9147f687e5636e0c2fd0b661ab5262c9e90faf/lib/elm-test.js#L404-L405). So you get no feedback when the code has some error like syntax error.
We might need to write a custom reporter (which is better than parsing JSON) and/or create a modified test runner.

If any of you have other ideas, please let me know. If not, I'll look into it when I have the time.

/cc @HairyRabbit, @vnhnhm, @radek-novak, @gabrielperales, @khudiakov, @bijanbwb

**Comment by kazk** [comment]
Elm support is coming soon. I'll add it to Codewars once the new version of [node-test-runner](https://github.com/rtfeldman/node-test-runner) gets out of beta and after testing against that.
Sorry for the delay. I had Elm 0.18 partially working, but 0.19 got released and I wanted to add that instead.
Also, if any of you have requests for packages, let me know so I can try to include it.

**Comment by kazk** [comment]
I just released Elm support! node-test-runner is still in beta, but I've tested against the latest `0.19-beta12` and only had a minor issue that I can workaround (opened a PR to fix it).

---

We obviously don't have any kata for Elm yet, so please help translating existing kata! I'll add Elm version to the Multiply kata for your reference very soon. I've also added a [wiki page for Elm](https://github.com/Codewars/codewars.com/wiki/Language-Elm) with basic examples.

I hope the setup feels natural. I did some post processing to the JSON output to have hierarchy like other languages. It should also keep the `Debug.log` output under the test case.

![image](https://user-images.githubusercontent.com/639336/48308457-3a9bce80-e51a-11e8-894c-95b9c6c33fc0.png)

The output of `ListDiff`/`CollectionDiff` is not as pretty as the one you see when running locally at the moment, but I'm planning to improve that later.

Please try it out and let me know if you find any issues. I'm excited to finally have Elm on Codewars :)

**Comment by kazk** [comment]
> It should also keep the `Debug.log` output under the test case.

Unfortunately, `Debug.log` outputs get messy once we have more tests. I'll see if there's a way to capture them per test. If not, I need to group them separately from the test cases.
