### ISSUE TITLE
Add Fortran 95 Support

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#553]
I've very recently started playing with Fortran and think that it has the potential to yet become another language supported by the CW platform.  Although Fortran is not very often used in production environments anymore, I think it would further add value to the CW community because interested Codewarriors can get to learn and experience programming in a language which is well over half a century old and predates even **C** by a full decade and a half.

With regards to the specification used, I would recommend Fortran 95 because:

1. It is a relatively new (although not the newest) version of Fortran
2. It appears to be the most taught version of Fortran online
3. ([The compiler](https://packages.ubuntu.com/trusty/gfortran) I happened to stumble upon turned out to be a Fortran 95 compiler 😛 )

****

@kazk I would happily contribute to this through a pull request within the next few months if I manage to figure everything out this time without stumbling too badly on the way.  However, I would also like to confirm that the Codewars Runner CLI rewrite isn't taking place within the next two to three months?  If the CLI rewrite is about to take place soon, please inform me as then I would probably postpone starting on my pull request until *after* the rewrite is complete, cheers 😃

**Comment by kazk** [comment]
@DonaldKellett

> However, I would also like to confirm that the Codewars Runner CLI rewrite isn't taking place within the next two to three months?

The rewrite has been taking place already, I completed 36 languages with some version variations so far. We're working on setting up the infrastructure right now.

> If the CLI rewrite is about to take place soon, please inform me as then I would probably postpone starting on my pull request until after the rewrite is complete

Can you look into testing framework? Using which one and how to use it should be useful even after the rewrite. Don't write code because I don't want to waste your time.

**Comment by DonaldKellett** [comment]
Thanks for your input :smiley:  Since the CLI rewrite is already well underway, I will not start on a pull request ATM (just as you suggested) which should give me more time to familiarize myself with the language (so far, I've only written very simple programs such as a greeting function or simple fibonacci).  Once I feel that I am competent enough with the language and have enough spare time in my hands, I'll be sure to ping you again to confirm that the rewrite is complete, and if not, I can always wait :smile:

With regards to Fortran 95 testing frameworks, I just did a simple search yesterday and there appears to be a few, the more popular ones being FUnit and FRUIT (**F**ort**R**an **U**n**I**t **T**esting Framework), but both seem to be not maintained anymore - FUnit's official website doesn't seem to respond at all (in Safari at least, but I think it's more of a server problem than a browser problem) and FRUIT's wiki and documentation seem to be deleted (following their links give a "(404) Not Found" error).  Therefore, I think it would make more sense to write a custom CW-2 testing framework as a module (which should be comparatively easy once I figure out how to compile modules using other modules using the `gfortran` command).

**Comment by DonaldKellett** [comment]
@kazk When is the rewrite set to be complete?  I've played around with GNU Fortran for another few days and should now be ready to start the pull request at any moment 😄

**Comment by kazk** [comment]
@DonaldKellett 
The rewrite of code runner itself (this repo) has been mostly complete since mid November.

I honestly can't say when it'll be available though. We've been working on setting up infrastructure and adjusting the server to improve stability. We also have to decide which parts to open source and how to accept contributions.

If you want, you can create a small standalone project resembling kata for now. I wrote the new runner so that code from real world projects can be used with minimum changes (no change for some languages), so it won't be wasted.

**Comment by DonaldKellett** [comment]
@kazk Thanks for the quick reply.  Would you mind clarifying your statement regarding creating a "small standalone project"?  From your final statement "it won't be wasted", I'm assuming that the "small standalone project" is referring to a pull request that shouldn't be published just yet?

**Comment by kazk** [comment]
No, I meant you can create a project that doesn't rely on code runner.
For example, your own `DonaldKellett/fortran-kata` or something that illustrates how to install the compiler, how to run the code, and how to run the test.

To be clear, I only suggested this because you sounded like you wanted to start working on it as soon as possible and I don't know when we can accept your contribution yet. I thought you can work on it as standalone project, and contribute the test framework when we're ready. "it won't be wasted" because it should be possible to use the test framework as is.

The new runner is more uniform and abstract compared to this one and, in most cases, it only needs to know what command to execute and where to write files.

**Comment by DonaldKellett** [comment]
> No, I meant you can create a project that doesn't rely on code runner

Ah, I see, thanks :smile:

> "it won't be wasted" because it should be possible to use the test framework as is

Does that mean that my individual project doesn't necessarily have to use Docker as long as I can somehow demonstrate the code running with all tests (on `gfortran` installation, usage of custom testing framework etc.) behaving as expected?

**Comment by kazk** [comment]
What you've done so far looks fine.

I'd recommend spending more time looking into existing unit test frameworks before committing to write your own. It's not easy to write a custom test framework and I'd rather not maintain one if possible. If you decide to write one, you can contribute by submitting a PR containing it in the future.
We'll let you know when we're ready to accept contributions.

**Comment by DonaldKellett** [comment]
@kazk The custom CW-2 testing framework for GNU Fortran is now complete at https://github.com/DonaldKellett/fortran-kata, it can be added to this Repo whenever Codewars is ready to accept it :smile:

**Comment by kazk** [comment]
@DonaldKellett
Thanks! I just skimmed through the tests and looks pretty good.
Can you add test cases for errors? Both run-time and compile-time.

**Comment by DonaldKellett** [comment]
> Can you add test cases for errors? Both run-time and compile-time.

Added :smiley:

**Comment by DonaldKellett** [comment]
@kazk Apologies for the late reply, I have now added a newline character `\n` before every `<DESCRIBE::>`, `<IT::>`, `<COMPLETEDIN::>`, `<PASSED::>` and `<FAILED::>` to avoid the issue you mentioned above.

Feel free to ping me again if there are any other issues/enhancements that should be made to the Fortran 95 CW-2 testing framework :smile:

**Comment by DonaldKellett** [comment]
@kazk Just curious as to when Fortran will be available on preview / main site as a Beta language (or otherwise), either only in Kumites or as a fully supported programming language?  I've recently heard that certain features of the new runner have been deployed to preview already?

**Comment by kazk** [comment]
I'm planning to start deploying the new runner in few days. My original goal was to do it during last week, but it got delayed because of few issues. I'm thinking of opening an issue on [Codewars/codewars.com](https://github.com/Codewars/codewars.com) about it to let users know before I do.

The new runner does support some new languages/language versions including Fortran, but I'd like to wait a little before allowing them to be used on Codewars because this is a huge change. I basically refactored the runner (this repo) and the server (where the code is submitted), then rebuilt the infrastructure.

Maybe we can add new languages/language versions Kumite-only during this period. I'm not sure how Codewars UI works so I'll ask Jake about it.

---

> I've recently heard that certain features of the new runner have been deployed to preview already?

I haven't deployed it yet. But I've been mirroring the traffic to the new runner for the past few weeks to monitor the error rates and the performance. So maybe someone misunderstood that.

**Comment by kazk** [comment]
@DonaldKellett
The preview site has Fortran Kumite available. The editor is empty for some reason, so see https://github.com/Codewars/codewars.com/wiki/Language-Fortran for how to write tests. Let me know if you find anything weird.

**Comment by kazk** [comment]
Fortran Kumite is now available on the main site as well. Not allowing Kata creation yet.

**Comment by DonaldKellett** [comment]
Thanks @kazk for notifying , will start testing ASAP 😄

**Comment by DonaldKellett** [comment]
> The editor is empty for some reason, so see \<link\> for how to write tests

If by editor you mean the code window for Test Cases then I think this issue is already fixed (on the main site):

![2018-04-11 10 44 19](https://user-images.githubusercontent.com/7777884/38624129-e9bb6724-3dd9-11e8-85b6-17b4cea58035.png)
