### ISSUE TITLE
Add Java 11 Support

### ISSUE THREAD

**Issue by wollf92** [Codewars/codewars-runner-cli#555]
I'd like to see support for Java 9 added. Many features regarding easy types and streams were added and I'd like to use them on codewars like I use them in real life.

Thanks!

**Comment by javatlacati** [comment]
@wollf92  Do you know which modifications should be in the runner [gradle file](https://github.com/Codewars/codewars-runner-cli/blob/master/frameworks/java/build.gradle)?

**Comment by kazk** [comment]
I'll look into adding Java 9 (and JUnit 5) to the new runner after the migration.

**Comment by kazk** [comment]
Java 11 is now available. I'm planning to run a script to update existing kata, but not today.

**Comment by Voileexperiments** [comment]
@kazk [All Java katas has been updated to Java 11](https://github.com/codewars/codewars.com/wiki/List-of-Java-Kata-to-Update). However all katas that use reflective access will cause unsuppressible warning messages to STDERR since Java 9 [new security features are added to prevent cross-module reflection access](https://stackoverflow.com/a/50259167):

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by $PERPETRATOR (file:/home/codewarrior/java/classes/) to $VICTIM
WARNING: Please consider reporting this to the maintainers of $PERPETRATOR
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

In general it seems that Java is moving away from any kind of raw reflection usage (though you can still do JVM hacks via class loader hacks), so I suppose all katas that uses reflection directly might have to be retired at some point.
