### ISSUE TITLE
Add Rust version 1.25

### ISSUE THREAD

**Issue by Majora320** [Codewars/codewars-runner-cli#556]
The current Rust version is from February, and, since Rust is a very fast-evolving language, lacks quite a few features available in current Rust. Please bump the version, and perhaps add additional tests; a test for the ? operator (introduced in 1.22) would probably be enough.

**Comment by kazk** [comment]
Rust v1.23.0 was added to the new system with following crates:
- `rand`
- `num`
- `chrono`
- `regex`
- `text_io`
- `serde`, `serde_json`

This will be made available when we switch to the new system. I'm not sure how soon that will be, but we'll start testing against real traffic soon.

**Comment by kazk** [comment]
Updated Rust to 1.25. We're planning to release it tonight.

**Comment by flip111** [comment]
In the dropdown box the 1.25 version is not selectable and it's also not the default version.

**Comment by kazk** [comment]
@flip111 that's because the kata is not compatible with 1.25. Ask the author/translator to make it compatible and republish.

**Comment by flip111** [comment]
Maybe a nice idea to e-mail all the authors with a list of their katas which are not compatible? Since codewars has this information anyway. How do you determine that the kata is not compatible actually? I don't want to bother with the 1.15.1 compiler anymore, can i select all the katas that run on 1.25? I find it a big strange actually because since rust 1.0 it has a backwards compatibility promise .. so it should work on the new compiler too.

**Comment by kazk** [comment]
We changed the way how the tests are written when we added 1.25.
1.15.1 one contains lots of hacks to be backwards compatible with original implementation that didn't use Cargo. You can see the mess in https://github.com/Codewars/codewars-runner-cli/pull/466 if you're interested. 1.25 one is much more straightforward and maintainable.
See https://github.com/Codewars/codewars.com/wiki/Language-Rust for differences.

Also, minor changes like test output can be breaking change for us. Last time I checked, they're still working on the JSON output so we rely on parsing the unstructured output.
