### ISSUE TITLE
Refactor and restructure Python test framework

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#569]
Currently Python tests are run like this:

```python
test.describe('tests')
test.it('should pass')
test.assert_equals(mul(2,3), 6)
test.it('should pass too')
test.assert_equals(add(2,3), 5)
test.describe('more tests')
# ...
```

Which is not ideal because:
- No automatic closing of test blocks, which means we have to `print('<COMPLETEDIN::>')` in order for multiple `describe`/`it` blocks to be nested properly in the output display (and to the time display, currently we have to do the benchmarking ourselves :V)
- Unlike other language versions, there are no closures, we have to manually wrap it inside another function to not leak everything to global scope
- Similarly, no support for block-specific features (e.g `Test.describe` in JS accepts optional override arguments for timeouts, `Test.before`, ...)
- Not consistent with other languages (see point 2)
- Encourage people to disregard proper formatting and indent (seriously, who wants to read flat code? As if we didn't have enough crappy kata makers already...)
- etc etc etc...

To make Python test framework consistent with other languages, properly introduces scope/closure, and more natural to use/more managable, I'd suggest using `with` as kind of a context manager:

```python
with test.describe('tests') as d:
	with test.it('should pass') as f:
		test.assert_equals(mul(2,3), 6)
	with test.it('should pass too') as f:
		test.assert_equals(add(2,3), 5)
with test.describe('more tests') as d:
	# ...
```

Then we can open and close blocks effortlessly via the use of `__enter__` and `__exit__` (and do benchmarking too). They can also provide additionally arguments for some customizations.

(There are lots of things that can be changed, e.g maybe we can utilize those `d` and `f` to add some extra functionality, or refactor some test method to them? I don't know, but at least this seems infinitely better than what Python test framework is structure right now. Currently it's like, well, chaos that could only come from JS.)

**Comment by kazk** [comment]
Another issue is that `cw-2.py` terminates on first failure by default and the default behavior is inconsistent even within itself. It terminates unless the test used `expect` (`allow_raise=False`) :/

https://github.com/Codewars/codewars-runner-cli/blob/dbf943d62c8d6ed451d27ac1817c0f13b1de558c/frameworks/python/cw-2.py#L11
https://github.com/Codewars/codewars-runner-cli/blob/dbf943d62c8d6ed451d27ac1817c0f13b1de558c/frameworks/python/cw-2.py#L21
https://github.com/Codewars/codewars-runner-cli/blob/dbf943d62c8d6ed451d27ac1817c0f13b1de558c/frameworks/python/cw-2.py#L31

**Comment by Bubbler-4** [comment]
[Here](https://www.codewars.com/kumite/5a6fcd17fd8c0632ef00000d?sel=5a70027d0136a1b8440000c2) is my own kumite to implement some features Voile mentioned (plus some other common features and bugfixes). It's indeed clean and cool to write the test groupings using the `with` block.

However, the `with` block has its own caveat: it doesn't have its own scope, so the variables inside the block (including the one declared on the line `with ... as x`) leak to the global scope anyway.
[Try it online!](https://tio.run/##K6gsycjPM/7/PzknsbhYwVkjPykrNblE04pLAQhSUtMU4uNT80pSi@LjNYpTc9I0rRQKgAqRZSsyS6CSOgpaiUXpxXA1XIkKtgoGXOWZJRlAkzUVEosVkiEGgyQMwayCosy8Eo1ETS4Y4/9/AA "Python 3 – Try It Online")

And from [StackOverflow](https://stackoverflow.com/questions/291978/short-description-of-the-scoping-rules):
> Essentially, the only thing in Python that introduces a new scope is a function definition.

So the explicit closure by function definition is required after all. We don't even have IIFE in JS, so the best we can do would be as follows:

```python
def _test_suite():
    with test.describe(...) as describe:
        with test.it(...) as it:
            some test...
_test_suite()
```

Surely it's much cleaner than how the tests are written right now, but at least we'll have to show this skeleton code to the kata authors (I suggest to place this in the kata editor's default test fixture comment, and we'll need to rewrite the TwoOldestAges example too).

**Comment by Voileexperiments** [comment]
Currently the JS test framework injects code like this:

```javascript
function (){
                const GLOBAL_randomToken = global;
                /* preloaded stuff */;
/* user code */;
                (function() {
                    if (global != GLOBAL_randomToken) throw new Error('global was reassigned');
                    var Test = global.Test, describe = global.describe, it = global.it, before = global.before, after = global.after;
/* test fixture */;
                })();
            }
```

because the tests are run in a IIFE block after preloaded and user code there's an automatic closure. Maybe we can do the same thing to how Python code is injected?

**Comment by kazk** [comment]
@Bubbler-4 Yeah, backward compatibility will be an issue.
If Codewars' front end allowed more than one test frameworks, we could make `cw-3.py` and use that for newer Python kata while keeping `cw-2.py` (can also make `unittest` available on Codewars). I'm not sure how much effort is necessary to add that feature.

How about using decorators? I don't know much Python, but isn't a decorator a higher order function? Maybe we can use it to wrap a function for `<DESCRIBE::>`/`<IT::>`/`<COMPLETEDIN::>` and register tests (then provide a way to run all)?

**Comment by Bubbler-4** [comment]
@Voileexperiments It's a little more complicated in Python, because the entire test suite must be indented once in order to be embedded in the following block:

```python
def _test_suite():
    ...
_test_suite()
```

If I'm seeing it correctly, I'd edit the following section in lib/runners/python.js:71-79
```js
function cw2Code(opts) {
  return [
    defaultImports(opts),
    CW2_IMPORT,
    opts.setup,
    opts.solution,
    opts.fixture
  ].join('\n');
}
```
into this:
```js
function cw2Code(opts) {
  return [
    defaultImports(opts),
    CW2_IMPORT,
    opts.setup,
    opts.solution,
    'def _test_suite():',
    opts.fixture.split('\n').map(row => '    ' + row).join('\n'),
    '_test_suite()'
  ].join('\n');
}
```
Then it'll be at least close to what JS version does, since there's no `global` in Python.

@kazk That's a good idea too, so something like
```python
@describe('describe message')
def describe1():
    @it('it message')
    def it1():
        some test...
```
might work as well. This construct will take larger effort to implement, I guess, but I'll definitely give it a try (while keeping the backwards compatibility).

**Comment by Bubbler-4** [comment]
Okay, so here is [my second Kumite](https://www.codewars.com/kumite/5a714b44ba1bb51ee8000093?sel=5a714b44ba1bb51ee8000093), using the decorator approach this time.

Both `with` version and `decorator` version look good, and both can provide backward compatibility with ease. (I included old-style usage in my second kumite.)

`with` approach:
* May utilize the `describe` and `it` objects to extend the functionality further (e.g. bind the `before` and `after` to them?)
* Need some edits on the runner code in order to wrap the test in a closure

Decorator approach:
* No need to edit the runner code at all, it has own closure and runs auto**magical**ly
* Further extension to `describe` and `it` might be tedious
* A little bit more typing is needed to write a test fixture

How do you think, @Voileexperiments @kazk @jhoffner ?

**Comment by Voileexperiments** [comment]
`decorator` version is basically like how Java/C# test framework are implemented (using attributes to mark methods for testing and provide other testing functionalities). `with` version is more like how test framework are designed in JS/Ruby.

I guess I'm okay with both of them, if they have their respective pros and cons. Maybe we can provide both?

**Comment by Bubbler-4** [comment]
> Can you elaborate on this?

The first impression was maintaining a class vs. maintaining a nested function, where the latter is slightly harder to read or understand in general. However, essentially the main routine is the same in two versions (so requires the same length/complexity of code in one function body anyway). Then the decorator way is more concise in that regard, and I agree that it's the way to go.

> ...wouldn't Python's keyword arguments allow extending on that?

You're definitely right. It turns out that keyword arguments are a very strong feature of Python, so further extensions can be done as I did for `before` and `after`.

> ...because I want to eventually get rid of concatenation/wrapping. AFAIK concatenations are done for historical reasons (from 4 years ago) and it should be avoided if we can since it causes lots of confusions like with error messages and conflicts. So I don't want to add another wrapping now.

For this point, I believe we can just leave each `.py` file with their respective names, and import each of them sequentially. [More on modules and import statement](https://docs.python.org/3/tutorial/modules.html). In short, when a piece of script code is not inside `if __name__ == "__main__":` block, it's run exactly once when the whole module (file) is imported.

Therefore, I suggest to do something like this (we want everything to be in the global scope so that it works with existing katas):
```python
from preloaded import *
from solution import *
test = Test = __import__('cw-2')
# We can't do `from 'cw-2' import *`
# So here is a workaround as per https://stackoverflow.com/a/11007138
for key, val in vars(__import__('cw-2')).items():
    if key.startswith('__') and key.endswith('__'):
        continue
    vars()[key] = val
from fixture import *
```

In addition, we might be able to prevent file injection hacks by setting each file's permission (if my understanding of Docker image - as a kind of isolated Unix environment - is correct)? Probably [os.chmod and the like](https://docs.python.org/3.6/library/os.html?highlight=os%20chmod#os.chmod) could be helpful for that.

**Comment by kazk** [comment]
> Therefore, I suggest to do something like this 

Yeah, I did something very similar for `unittest` (used on Qualified.io) in #552. Nice to see a possibility to do similar for `cw-2.py`.

> In addition, we might be able to prevent file injection hacks by setting each file's permission

Yeah, that's definitely possible. Also, it should be possible to prevent cheating by mutating `test/Test` (#431) by loading `solution` before `test = Test = __import__('cw-2')` like your example.

This is looking great. Thanks for the Unicode fix too! I haven't had the time to look into them (#558, #508, #545).

**Comment by kazk** [comment]
@Bubbler-4 thanks for the info about `six`, I've seen it used before. I need to clean up the list of supported packages and versions for the new runner so I'll probably install it explicitly while I'm at it.

**Comment by kazk** [comment]
Closing this as it's been deployed. @Bubbler-4 thanks for your awesome work!
