### ISSUE TITLE
Node/Babel syntax error feedback is awful

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#577]
When I have syntax error in any other language, at least it'll give a useful error message by telling what where is wrong, and what is wrong.

Except Node/Babel version:

![default](https://user-images.githubusercontent.com/14909989/36819306-f5197006-1d23-11e8-92d6-7fed78b35363.png)

It makes doing katas about JS/React a big pain.

**Comment by kazk** [comment]
Error messages are currently removed (I think this was done because concatenation makes it confusing).

https://github.com/Codewars/codewars-runner-cli/blob/898b466ad65a78a2fd46c5fdd8c6652144af97b0/lib/runners/javascript/index.js#L55-L63

I removed this in the new runner because I think it's better than nothing. I also avoided `node -e`. So once the new runner is deployed, it should give better error message.

Here's an example I just got from the logs.
```
SyntaxError: /home/codewarrior/index.js: Unexpected token, expected , (14:59)
  12 |     return null;
  13 |   }
> 14 |   return new Node(Number(string[0]), parse(string.slice(5));
     |                                                            ^
  15 | }
    at Parser.pp$5.raise (/runner/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/runner/node_modules/babylon/lib/index.js:1761:8)
```

**Comment by kazk** [comment]
Sorry, the snippet above is not responsible for the Babel error message. Currently errors from Babel is limited because of the following code:
https://github.com/Codewars/codewars-runner-cli/blob/898b466ad65a78a2fd46c5fdd8c6652144af97b0/lib/runners/javascript/transform.js#L53-L66

I'm guessing the same intention (not to confuse the users), but I agree this is not helpful at all. Anyways, the new runner will have better output.

**Comment by kazk** [comment]
The new runner should show better error message now. The line numbers won't match, but it's better than nothing.
