### ISSUE TITLE
Warning in rust fails Kata

### ISSUE THREAD

**Issue by AdamSzopa** [Codewars/codewars-runner-cli#588]
hi,
While training on https://www.codewars.com/kata/string-repeat/train/rust I noticed that even though the tests pass, the attempt is marked as failed due to warnings of unused code:

```
warning: function is never used: `repeat_str`
 --> src/lib.rs:1:1
  |
1 | fn repeat_str(src: &str, count: usize) -> String {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

warning: function is never used: `solution`
  --> src/lib.rs:22:1
   |
22 | fn solution(src: &str, count: usize) -> String {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: struct is never used: `RandAscii`
  --> src/lib.rs:27:1
   |
27 | struct RandAscii;
   | ^^^^^^^^^^^^^^^^^

warning: function is never used: `solution`
  --> src/lib.rs:22:1
   |
22 | fn solution(src: &str, count: usize) -> String {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default
```

The warning seem to trigger on internal stuff, unavoidable for the user

**Comment by kazk** [comment]
Do you have 1.25 selected? There's some issues with `1.25` at the moment.

**Comment by AdamSzopa** [comment]
Yup, 1.25
Let me know if I can help troubleshoot or test.

pt., 13 kwi 2018, 21:42 użytkownik kazk <notifications@github.com> napisał:

**Comment by kazk** [comment]
Turns out those are considered unused because they're not public or used from `main` (which doesn't exist in this case).
I want to keep most of the default warnings because they're usually very helpful, but I'll add `-Adead_code` to `RUSTFLAGS` to disable this one because Codewars treats anything in stderr as error at the moment and the only way to avoid this is to make everything public.

I'll let you know when the fix is deployed.

**Comment by kazk** [comment]
I've deployed the fix. Let me know if it still doesn't work.
