### ISSUE TITLE
Haskell GHC 7.10.3 test results are incorrectly nested

### ISSUE THREAD

**Issue by anka-213** [codewars/codewars-runner-cli#624]
The results from Hspec are more deeply nested than they should be.

For example:

```haskell
module Codewars.Kata.PrFactors.Test (main) where
import Codewars.Kata.PrFactors
import Test.Hspec
import Test.HUnit

main = hspec $ do
    describe "PrFactors" $ do 
      describe "primes" $ do
          it "has correct primes" $ do
              take 10 primes `shouldBe` [2,3,5,7,11,13,17,19,23,29]
    describe "isPrime" $ do
        it "Gives correct answer for 7919" $ do
            isPrime 7919 `shouldBe` True
        it "Gives correct answer for 49" $ do
            isPrime 49 `shouldBe` False
    describe "prime_factors" $ do
        it "1st series" $ do
            prime_factors(7775460) `shouldBe` "(2**2)(3**3)(5)(7)(11**2)(17)"
            prime_factors(7919) `shouldBe` "(7919)"
```

will nest the results like this:

```
Test Results:
 PrFactors >
   primes >
      has correct primes
   isPrime >
     Gives correct answer for 7919
     Gives correct answer for 49
     prime_factors >
        1st series
```

The expected nesting would be:

```
Test Results:
 PrFactors >
   primes >
      has correct primes
 isPrime >
   Gives correct answer for 7919
   Gives correct answer for 49
 prime_factors >
   1st series
```

In other words, each item is nested under the previous one, instead of being listed as a separate categories as the source code specified.

**Comment by kazk** [comment]
Yeah, the test output for GHC 7.10.3 is incorrect. See https://github.com/Codewars/codewars-runner-cli/issues/454#issuecomment-315211748 for the reason. As far as I know, it's been like that since it was created.

GHC 8 one should be correct.
I'm not going to fix the old one, but maybe someone can when we start accepting contributions again in the future.

**Comment by kazk** [comment]
It's been available on Codewars already.

To use it on older kata, the tests needs to be updated because the way tests are defined changed.
GHC 8 one needs `spec :: Spec` and the name of the module must end with `Spec`. `main` can be kept for backwards compatibility.
Something like the following should work as long as it's not using deprecated features.

```haskell
module Codewars.Kata.PrFactorsSpec where

import Test.Hspec
import Codewars.Kata.PrFactors

spec :: Spec
spec = do
    describe "PrFactors" $ do 
      describe "primes" $ do
          it "has correct primes" $ do
              take 10 primes `shouldBe` [2,3,5,7,11,13,17,19,23,29]
    describe "isPrime" $ do
        it "Gives correct answer for 7919" $ do
            isPrime 7919 `shouldBe` True
        it "Gives correct answer for 49" $ do
            isPrime 49 `shouldBe` False
    describe "prime_factors" $ do
        it "1st series" $ do
            prime_factors(7775460) `shouldBe` "(2**2)(3**3)(5)(7)(11**2)(17)"
            prime_factors(7919) `shouldBe` "(7919)"

main = hspec spec
```
See [the wiki](https://github.com/Codewars/codewars.com/wiki/Language-Haskell) for more details.

**Comment by kazk** [comment]
Closing because almost all kata is now using GHC 8.
