### ISSUE TITLE
Never-ending recursion filling up the stdout prevents tests from running

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars-runner-cli#637]
For some reason if stdout is filled up while testing a function (function is recursive - could be a potential reason?), the runner may stop executing the test **without throwing an error**, and execute no tests afterward. If at least 1 test was passed successfully before this happens - the whole suite "gets passed" (as the number of passes is `> 0`, number of fails and errors `== 0`).

This was found out with [this solution](https://www.codewars.com/kumite/5b8976bb75b546faa30000be?sel=5b8976bb75b546faa30000be). Here's a link to [my fork](https://www.codewars.com/kumite/5b8976bb75b546faa30000be?sel=5b8981ff97953225bb00002f) with some additional comments. If I manage to replicate the issue, I'll provide more info.

**Comment by FArekkusu** [comment]
Confirmed it with [this kumite](https://www.codewars.com/kumite/5b89882e74a4f4b9bc000125?sel=5b89882e74a4f4b9bc000125). If a recursive function fills up the stdout without ever exiting the recursion, the execution stop, and no further tests are executed. Passing at least 1 test before doing the trick will make you "pass everything".

**Comment by kazk** [comment]
Thanks for reporting. I'll look into this.

Once the maximum allowed amount is written to stdout, the container is killed and the exit code is set to `1`. So it shouldn't allow it to pass even the number of failure is `0`.

**Comment by kazk** [comment]
For your kumite, it looks like it's killed before reaching the max amount for some reason :/

**Comment by kazk** [comment]
This is most likely a bug of the test framework. `cw-2.js` swallows errors when not in `async` mode :|

https://github.com/Codewars/codewars-runner-cli/blob/d1c1d8bfb9919ee61d520370484894be27f48739/frameworks/javascript/cw-2.js#L32-L37

The maximum call stack error appears if I add `else { throw err; }` there. I'm not sure why removing the `console.log` also fixes the issue though.

Honestly, `cw-2.js` is a real mess and I'm not sure what's going on. I don't even know why it's handling `uncaughtException` like that.

I'll try to dig into this little more and maybe just remove that. I'll close this when the fix is deployed.

**Comment by FArekkusu** [comment]
My kumite doesn't work anymore, but the solution I've mentioned in the first comment still does. Here's a screenshot of a fork I've just made and the exploit is still working.

![Exploit in action](https://imgur.com/8NATxTV)

**Comment by Voileexperiments** [comment]
Looks like this is related to #739

**Comment by kazk** [comment]
Closing because this doesn't seem to happen in newer Node version.
