### ISSUE TITLE
Throwing a callable function in JS halts the tests without triggering errors

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#643]
If any callable function is thrown inside either a `describe` or `it` block (e.g by code inside user function), the tests is completely halted but no errors are thrown, effectively stops any further code from running. e.g:

```javascript
Test.describe('abc',function() {
  Test.pass();
  throw _=>_;
  Test.fail();
})
```

![image](https://user-images.githubusercontent.com/14909989/46326932-c6742e00-c631-11e8-9177-c206e197b71f.png)

When it's not run inside a `describe` or `it` block, the correct behaviour happens:

![image](https://user-images.githubusercontent.com/14909989/46326951-e0ae0c00-c631-11e8-9254-568e37abbb65.png)

**Comment by kazk** [comment]
This is because of `handleError` function:

https://github.com/Codewars/codewars-runner-cli/blob/d1c1d8bfb9919ee61d520370484894be27f48739/frameworks/javascript/cw-2.js#L235-L253

is used to process whatever thrown when inside `describe` and `it`. `ex` is `_ => _` in your example and `ex()` doesn't throw.

I guess it's written this way because it's also used to wrap the entire code:

https://github.com/Codewars/codewars-runner-cli/blob/d1c1d8bfb9919ee61d520370484894be27f48739/lib/runners/javascript/index.js#L155-L164

and this is why it works as expected when outside of `describe`/`it`.

**Comment by Voileexperiments** [comment]
Maybe the exception should be thrown at the end anyways, because errors should not happen. aka like this:

```
   if (typeof ex == "function") { 
     try { 
       ex(); 
     } 
     catch (ex) { 
       this.handleError(ex); 
     } 
     throw ex;
   } 
```

**Comment by kazk** [comment]
I just read how you found this issue.
Writing `throw Error` by mistake can happen and this will be super confusing.

**Comment by kazk** [comment]
I'll try fixing this by special casing when it's used to wrap the entire code.

Maybe naming the wrapper function
```javascript
Test.handleError(function someName() {
});
```
and checking
```javascript
if (typeof ex == "function" && ex.name == "someName") { 
```
will work.

At least, this will prevent triggering this accidentally.

**Comment by kazk** [comment]
This will be resolved by deprecating cw-2.

**Comment by kazk** [comment]
Closing because `cw-2` is now considered deprecated.
