### ISSUE TITLE
Add Kotlin 1.3

### ISSUE THREAD

**Issue by kdmatrosov** [Codewars/codewars-runner-cli#649]
Please complete the following information:

- Name: Kotlin
- Version: 1.3
- Release Note/Changelog: [https://kotlinlang.org/docs/reference/whatsnew13.html](https://kotlinlang.org/docs/reference/whatsnew13.html)

---
It would be grateful to see unsigned intergers and Standard library's updates

**Comment by javatlacati** [comment]
Tah includes the new Random class from Kotlin

**Comment by shivawu** [comment]
Up. There seems to be some incompatible changes in the stdlib and coroutine becomes stable. Right now it's actually not trivial to get a kotlin 1.2 project setup anymore (using gradle)...

**Comment by kazk** [comment]
Kotlin 1.3.21 is ready to be deployed. I'll close this when it's deployed and made available on Codewars.

**Comment by kazk** [comment]
Kotlin 1.3 is now available on Codewars. Existing kata was updated if compatible (195/200).

**Comment by Voileexperiments** [comment]
@kazk the remaining Kotlin kata ([To BrainFuck Transpiler](https://www.codewars.com/kata/59f9cad032b8b91e12000035/kotlin)) is timing out because Kotlin compile time and JVM startup time is too slow :( At the moment compiling `Multiply` on Kotlin already takes 6 seconds and compiling this kata's code takes 11-12 seconds. It's simply outrageous (basically #333 again).

Why is the timeout set to 12 seconds? [The repo](https://github.com/codewars/codewars-runner-cli/blob/master/lib/config.js) seems to say the intended value is otherwise.

**Comment by kazk** [comment]
Kotlin timeouts have been 12s since [2018-05-18](https://github.com/Codewars/codewars.com/wiki/Language-Kotlin). The new runner is much faster (it used to take twice as long to compile). Also, this repository has been irrelevant for years so don't use this as the source of truth.

I think 12s should be enough for 99.9% of the challenges on Codewars, but I'll increase the time limit to 16s.

**Comment by Voileexperiments** [comment]
Also, I discovered that stdout is not flushed after each test assertions in Kotlin 1.3 (it does in Kotlin 1.2). Is it intended?

**Comment by kazk** [comment]
There's no difference on our end between the two versions. Probably something to do with the test framework versions.

Or maybe Kotlin 1.3 is taking more than 12s to compile and the tests are not even executed yet.

**Comment by kazk** [comment]
Looks like it's the latter.

![image](https://user-images.githubusercontent.com/639336/81008668-27fd0f80-8e08-11ea-8793-069ca9b5c569.png)
