### ISSUE TITLE
Add Dart 2.1

### ISSUE THREAD

**Issue by nickmeinhold** [Codewars/codewars-runner-cli#650]
- Name: Dart
- Version: 2
- Release Note/Changelog: https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md

---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Dart 2.1.1 is almost ready.
Files are not concatenated anymore and test output supports proper grouping like most of the other languages.

**Comment by kazk** [comment]
Dart 2.1 is now on Codewars. See https://github.com/Codewars/codewars.com/wiki/Language-Dart for how to write tests.

**Comment by kazk** [comment]
I've updated most of the existing Dart kata to 2.1.

[Algebraic Isomorphism](https://www.codewars.com/kata/5917f22dd2563a36a200009c/dart) (2 kyu) and [To BrainFuck Transpiler](https://www.codewars.com/kata/59f9cad032b8b91e12000035/dart) (1 kyu) are the only ones left. These are very difficult to update so it might not be available in 2.1 for a while.

**Comment by Voileexperiments** [comment]
@kazk Please ***remove*** the Dart language version for To BrainFuck Transpiler because the test code is reinventing the wheel from the ground and deeply coupled with the runner backend's output:

![image](https://user-images.githubusercontent.com/14909989/80960412-5f38e400-8e3b-11ea-901f-4200281b57ef.png)

So it cannot be fixed without completely rewriting the test code from scratch. It's beyond broken right now because of that, and it doesn't have any solves anyway, so it really should've been ~~nuked from orbit~~ removed.

Again, I cannot express enough how corrupted this test code is.

**Comment by ice1000** [comment]
Plus: let's delete the dart translation of https://www.codewars.com/kata/5917f22dd2563a36a200009c/dart because we need to migrate to dart 2

**Comment by Voileexperiments** [comment]
@kazk I just checked Algebraic Isomorphism again and it requires [declaration-site variance](https://github.com/dart-lang/language/issues/524), which requires Dart 2.4 or above. So currently it *cannot* be fixed.

...Also apparently Dart 1.x has no sound type checking whatsoever. What a great news :facepalm:
