### ISSUE TITLE
Different languages have different behaviours on what constitutes a passed/failed test

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#656]
In JS, Python and Ruby, whenever an `Test.assertEquals` is called, a test result is generated (either `Test passed` or `Test failed`).

In C++, however, the entire `It` block is the test: `Assert::That` only aborts testing and make the block counts as a failed tests if assertion fails. If it succeeds, nothing is generated.

Similarly, in C# and Java, even if you have 1000 assertions in a test method, only 1 result is seen. C# can make every test a separate test if `TestCase` attribute is used, but that generates an entire block for every attribute added so it's not the same. (It also doesn't allow doing this dynamically.)

They're inconsistent with each other and make consistent test result formatting across multiple languages difficult, if not impossible.

**Comment by kazk** [comment]
Closing as wontfix because making different test frameworks from different languages behave consistently is impossible.

Codewars' frameworks are weird because the assertion functions/methods are responsible for generating the test result for some reason.
I hate them and have been thinking of ways to get rid of them. Qualified doesn't use them either for anything new and the old challenges are being converted.

For cw-2.js, I tried to write some script using [jscodeshift](https://github.com/facebook/jscodeshift) that transforms cw-2.js tests to Mocha. But I saw some authors use the test framework in a very "creative" way (e.g., `describe` only containing `console.log`) and gave up.
