### ISSUE TITLE
Upgrade junit to junit 5

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#662]
Currently the junit version is `4.12` according to `junit.runner.Version.id()`.

Can it be upgraded to junit 5? There are some very useful features, e.g [`@DisplayName`](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/DisplayName.html) annotation.

**Comment by kazk** [comment]
The new code runner uses JUnit 5's "JUnit Platform Launcher API" to run tests (it supports running tests written in JUnit 4 through `junit-vintage-engine`).

To write tests in JUnit 5, you just need to use the new APIs under `org.junit.jupiter` instead.

```java
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

class AdderTests {
  @Test
  void testAdd() {
    assertEquals(2, Adder.add(1, 1), "1 + 1 should equal 2");
  }
}
```

`@DisplayName` and nested tests are supported.

---

The reason why this is not documented is that Codewars can only have one test framework per language at the moment and I didn't like the idea of having `junit` identifier to mean multiple versions of JUnit with different APIs (Qualified have been using this and have identifiers `junit` and `junit5`).
But this was before I knew Codewars code base and how difficult it is to change it. I'm now ok with users using it because I don't think I can add proper support any time soon and I should be able to fix the data later.
