### ISSUE TITLE
Add Typescript 3.3

### ISSUE THREAD

**Issue by SorenTheBrave** [Codewars/codewars-runner-cli#668]
- Name: Typescript
- Version: 3.2

**Comment by shivawu** [comment]
Up this. I would suggest go all the way up to 3.2, since it's already there and totally (in my experience) backward compatible.

**Comment by kazk** [comment]
Added TypeScript 3.3. 197 kata wasn't compatible. I'll find out why and document  steps to them later.

**Comment by SorenTheBrave** [comment]
Hooray! Thank you kazk :)

**Comment by kazk** [comment]
Here's a [list of TypeScript kata that needs update](https://github.com/Codewars/codewars.com/wiki/List-of-TypeScript-Kata-to-Update-to-3.3). Most of them seems like they have implicit `any` somewhere on the author's side (reference solution, test helpers). Maybe they just copied JavaScript version.

Any help updating them will be appreciated.

**Comment by shivawu** [comment]
Thanks @kazk! Would be love to help. Since I've never done that, is there a tutorial where I can get started? Can I contribute to a kata that's somebody else? or hasn't solved myself?

**Comment by kazk** [comment]
@shivawu Thanks! See https://github.com/Codewars/codewars-runner-cli/issues/690#issuecomment-461599685 for how to do it.

That example is for Rust, but it's the same work flow. It'll tell you what's wrong when you validate solution with the language version set to 3.3. I've fixed some and it was mostly just missing types.

I'd recommend solving them first because you won't be able to gain progress after editing kata.
