### ISSUE TITLE
Add Rust version 1.33.0

### ISSUE THREAD

**Issue by LesnyRumcajs** [Codewars/codewars-runner-cli#690]
Please complete the following information:

- Name: Rust
- Version: 1.32.0
---
Couldn't find a better category. It would be nice to have newest Rust available on Codewars. It would be even nicer if existing katas would have access to this new Rust version (or at least 1.25). Katas created with Rust 1.15 are most probably finishable with higher version of Rust because of it's renowned backward compatibility (they run tests with major crates to check this, I guess katas are not as complicated as Diesel, Serde or Hyper. It makes me a little bit sad when I finish writing the code, get compiler error, and finally notice that the particular kata is for 1.15 exclusively.

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Yeah, I've been wanting to add a newer version and get rid of 1.15.

Rust on Codewars was originally contributed by the community, then I rewrote it so we can use Cargo while keeping it compatible (#466). So 1.15 on Codewars is a hack. When I added 1.25, I removed most of the hacks and that's why it's not compatible. See [Rust wiki page](https://github.com/Codewars/codewars.com/wiki/Language-Rust#test-frameworks) for the differences.

Also, the test output is manually parsed and it's not standardized so this changes between versions. I've been waiting for the JSON output that was proposed years ago, but I don't think it's been finalized yet :(

It's more work than it seems.

**Comment by LesnyRumcajs** [comment]
I see. Thanks for the feedback.

**Comment by kazk** [comment]
I just created a new wiki page of a [list of Rust 1.15 kata](https://github.com/Codewars/codewars.com/wiki/List-of-Rust-1.15-Kata-To-Update) to be updated.
You can use that to avoid them or help us update :)

We currently have `117` kata with `1.25` enabled and `95` with `1.15`.

**Comment by LesnyRumcajs** [comment]
Great, I'll get to it. :)

**Comment by hedgehog1024** [comment]
> I just created a new wiki page of a list of Rust 1.15 kata to be updated.
You can use that to avoid them or help us update :)

I wish to help. However, I see no way to translate a kata from one Rust version to another. How one can do it?

**Comment by kazk** [comment]
@hedgehog1024 Thanks :)

You've completed ["Don't give me five!"](https://www.codewars.com/kata/dont-give-me-five/rust) so I'll use that for example.

When changing language version, we usually just do it by editing kata. So open the kata editor by clicking "Edit Kata".

![image](https://user-images.githubusercontent.com/639336/52442289-98b75e00-2ad7-11e9-96b4-456cae15813e.png)

The original test looks like the following:

```rust
// At the moment random tests are not possible for RUST
// https://github.com/Codewars/codewars-runner-cli/issues/240

#[test]
fn basic_tests() {
    assert_eq!(dont_give_me_five(1, 9), 8);
    assert_eq!(dont_give_me_five(4, 17), 12);
}

#[test]
fn advanced_tests() {
    assert_eq!(dont_give_me_five(1, 90), 72);
    assert_eq!(dont_give_me_five(-4, 17), 20);
    assert_eq!(dont_give_me_five(-4, 37), 38);
    assert_eq!(dont_give_me_five(-14, -1), 13);
    assert_eq!(dont_give_me_five(-14, -6), 9);
}
```
(BTW, it's possible to add random tests even on 1.15)

To change this to make it compatible with 1.25, we need to put them inside a child module `tests`.

```rust
#[cfg(test)]
mod tests {
use dont_give_me_five;

// TODO add random tests

#[test]
fn basic_tests() {
    assert_eq!(dont_give_me_five(1, 9), 8);
    assert_eq!(dont_give_me_five(4, 17), 12);
}

#[test]
fn advanced_tests() {
    assert_eq!(dont_give_me_five(1, 90), 72);
    assert_eq!(dont_give_me_five(-4, 17), 20);
    assert_eq!(dont_give_me_five(-4, 37), 38);
    assert_eq!(dont_give_me_five(-14, -1), 13);
    assert_eq!(dont_give_me_five(-14, -6), 9);
}
}
```

```diff
+ #[cfg(test)]
+ mod tests {
+ use dont_give_me_five;
 
+ }
```

You can verify this by clicking "Validate Solution" after changing the language version to 1.25. Don't forget to also update the "Example Test Cases".

![image](https://user-images.githubusercontent.com/639336/52442896-32cbd600-2ad9-11e9-899f-63ebafde57da.png)

When you're done, just click "Re-Publish" (this might take some to finish).

![image](https://user-images.githubusercontent.com/639336/52443216-fe0c4e80-2ad9-11e9-9fb6-35258d57f72c.png)

To use crates like `rand`, do something like the following:

```rust
#[cfg(test)]
extern crate rand;

#[cfg(test)]
mod tests {
    use add; // function to test
    use rand;
    use rand::distributions::{IndependentSample, Range};
    #[test]
    fn returns_sum() {
        let between = Range::new(1, 10);
        let mut rng = rand::thread_rng();
        let x = between.ind_sample(&mut rng);
        let y = between.ind_sample(&mut rng);
        assert_eq!(add(x, y), x + y);
    }
}
```

**Comment by LesnyRumcajs** [comment]
Acutally I don't have edit kata option. Is higher kyu required for this?
![image](https://user-images.githubusercontent.com/9642092/52443820-0474e780-2b27-11e9-99b0-fec905ac9147.png)

**Comment by kazk** [comment]
You're right. I completely forgot about that :( You need 4000 honor points. See this [table](https://github.com/Codewars/codewars.com/wiki/Privileges#table).

**Comment by LesnyRumcajs** [comment]
Grinding time!

**Comment by LesnyRumcajs** [comment]
@kazk  are you positive 4000 honor points is the only requirement? I still can't edit katas the way you described it.

![image](https://user-images.githubusercontent.com/9642092/52532866-977e6f00-2d2b-11e9-8dba-aa8b85eb2217.png)

**Comment by kazk** [comment]
@LesnyRumcajs 4000 honor points should be the only requirement from a user. It should show "Edit Kata" if you have 4000 points and the kata doesn't have contribution disabled.

It can be a cache issue if you had loaded that page before. Can you try if "Edit Kata" shows on other kata?

**Comment by LesnyRumcajs** [comment]
@kazk Ya, I relogged, cleared the cache and checked out even from a different machine. Strangely I hadn't received any notification about my new super powers when passed 4k.

**Comment by kazk** [comment]
@LesnyRumcajs Something might be broken. It'll be tracked on https://github.com/Codewars/codewars.com/issues/1723

**Comment by LesnyRumcajs** [comment]
@kazk  Okay, I'm starting to update the katas. If I can't edit it (no issues in past week, contributing disabled), should I add an issue so the kata author will do it himself / herself (or wait till I can do it myself)?

**Comment by kazk** [comment]
@LesnyRumcajs Thanks!
I'd suggest creating a suggestion comment with a link to the wiki page.

Something like:

> Need to Rust to 1.25. See [List of Rust 1.15 Kata to Update](https://github.com/Codewars/codewars.com/wiki/List-of-Rust-1.15-Kata-to-Update).

That's what the other user helping to update Haskell is doing.

**Comment by kazk** [comment]
@LesnyRumcajs I think I can add Rust 1.32 soon (luckily the test output looks the same).

The only issue I've found so far is `rand`. Rust 1.25 has `0.4.2` and I'd like to update to the latest `0.6.5` for Rust 1.32. So any kata using `rand` needs to be [updated](https://rust-random.github.io/book/update.html) in order to make it compatible.

I'll probably wait for [Rust 1.33 (2019-02-28)](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1330-2019-02-28) though. I hope changes from 1.32 doesn't affect us.

---

For future versions, I'd like to have at most 2 versions at the same time. We can add a new version when all of the kata using older versions are updated to newer one. I'm going to make 1.33 an exception because 1.15 is a huge hack and requires larger effort to update to 1.25.

So for now we can have versions:

- 1.15
- 1.25
- 1.33

Next step is to drop 1.15 by updating existing kata using it to 1.25+:

- 1.25
- 1.33

Then, before adding another version, I'll ask the community to update any kata using older version to newer one so we can drop the older one. I'll help with making a list of kata to update and also run a script to update them if it's compatible without code change.

If we need significant change for some reason, I'll consider adding a version temporarily.

**Comment by bartsmykla** [comment]
Hi @kazk is there a way to help creators of Katas to move from 1.15 to newer ones, or they need to do that themselves?

**Comment by LesnyRumcajs** [comment]
@bartsmykla  You can help by following @kazk guide here: https://github.com/Codewars/codewars-runner-cli/issues/690#issuecomment-461599685

**Comment by kazk** [comment]
@bartsmykla Thanks. You can also post a comment suggesting an update and maybe others can help. See https://github.com/Codewars/codewars-runner-cli/issues/690#issuecomment-462875755

**Comment by kazk** [comment]
Added Rust 1.33!

I ran a script to update compatible kata to use 1.33 and looks like we have 164 kata with 1.33 enabled.
