### ISSUE TITLE
Options to contribute ??

### ISSUE THREAD

**Issue by flip111** [Codewars/codewars-runner-cli#695]
After this repository went obsolete it became less clear what the option to contribute are. I guess the technology of codewars-runner-cli got upgraded and is now proprietary. Fine. Is there still opportunity for the community to be helpful in any way to codewars? Especially about language support what this repository was about.

Maybe some API or specification can be defined that a language can implement to be codewars compatible?

At least it would be good to have a page or list of things the community can pick up. Such as https://github.com/Codewars/codewars-runner-cli/issues/690#issuecomment-461219529

If such a page already exists it would be very good to put it in the readme of this repository.

**Comment by kazk** [comment]
> Is there still opportunity for the community to be helpful in any way to codewars?

Yes, but currently it's very unclear as you described. I'd like to eventually open source most of the parts but I haven't got to it yet.

> Especially about language support what this repository was about.
>
> Maybe some API or specification can be defined that a language can implement to be codewars compatible?

For language request, there's no standard way to contribute at the moment. The new runner is very simple and it usually doesn't require anything special except for the [test output format](https://github.com/Codewars/codewars-runner-cli/blob/master/documentation/output_format.md).

The issue template will ask for necessary information and that's usually enough for me to implement. I'll ask for more information and help when it becomes necessary.

Users can still contribute code when necessary:

- a user contributed a new test framework for Fortran support #553
- a user contributed a new Haskell package to be included after discussing in #691

So if you have something you'd like to contribute, please open a new issue. We can work from there.

For contributing to Codewars kata (like updating for Rust), I've created few wiki pages and those can be found in the sidebar of [Codewars wiki](https://github.com/Codewars/codewars.com/wiki).

Thanks for considering to contribute. Feel free to continue posting comments if you have further questions.

**Comment by azzamsa** [comment]
> I'd like to eventually open source most of the parts but I haven't got to it yet.

@kazk is that mean codewars.com codebase will be open source in near future ?

**Comment by kazk** [comment]
@azzamsa no not Codewars. Just parts of the new code runner like customized/custom test frameworks, test reporters, and Dockerfiles.

For Codewars, I've been turning new features into a community project like [codemirror-agda](https://github.com/Codewars/codemirror-agda). Maybe we'll expand in the future.

**Comment by DanL12186** [comment]
Any chance we'll ever be able to take a shot at improving Codewars' general performance? 

Maybe it's just a server/money issue (hard to tell), but finding and killing N+1s, general query optimization, updating gems/libraries (all things that take time, and are understandably too time-consuming for just one person), image optimization (CW loads all full-sized GH pictures but only displays them at around 64x64, when much smaller thumbs on GH exist), etc could probably still help a fair bit, even if the TTFB is hard to improve for free.

**Comment by kazk** [comment]
@DanL12186 You've been commenting on this on Gitter and I've explained multiple times already. See my last comment (reposted on GitHub issue) https://github.com/Codewars/codewars.com/issues/1784#issuecomment-513944396 for why it's unrealistic.

- finding and killing N+1s and general query optimization
  - Some of the innefficiencies are unavoidable as long as MongoDB is used and it's also buried under the ORM. Obvious ones are mostly done.
  - We're planning to update the database version and I'm hoping this will resolve some of the issues. Codewars is currently using very old version and it was a lot of work just to make it ready to update.
- updating gems/libraries
  - Updating is not the difficult part and I've already updated where it's possible. The remaining ones requires significant work due to breaking changes.
- image optimization (CW loads all full-sized GH pictures but only displays them at around 64x64, when much smaller thumbs on GH exist)
  - This should be pretty easy to fix (unless Codewars does something strange)

The best way to help for now is to open issues about small fixes like the last one. Can you do that?
