### ISSUE TITLE
Add Effects library for Idris

### ISSUE THREAD

**Issue by ice1000** [Codewars/codewars-runner-cli#716]
- Name: Effects
- Language Name: Idris
- Website: http://docs.idris-lang.org/en/latest/effects/introduction.html

- Why is this useful?
  - For testing with random numbers
- Example Code:
  - `import Effects`

**Comment by ice1000** [comment]
What do you mean by status/ready? Can I have the library now?

**Comment by kazk** [comment]
It means ready to be deployed (you should see the description if you hover over it or if you go to labels page). I'll close the issue when it's deployed, same as forbidding the hole.

I'm out of office today and didn't want to release it because it has some changes unrelated to this that might affect other services.

**Comment by ice1000** [comment]
Thanks!

**Comment by kazk** [comment]
Deployed
