### ISSUE TITLE
`assert` should not be made available in Node v6/v8 Codewars

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#732]
`assert` are available by default in Node v6 and v8 Codewars (Mocha and Node v10 requires manually importing it first). However if I run something like this:

```
describe('123', function() {
  it('456', function() {
    assert.equal(0,1);
  });
});
```

The result is good in v6:

![image](https://user-images.githubusercontent.com/14909989/55276039-2a4d8a00-5329-11e9-9a9f-33d46f84a289.png)

But broken in v8:

![image](https://user-images.githubusercontent.com/14909989/55276044-494c1c00-5329-11e9-94f3-8136e86772db.png)

But both of them are broken actually, because a successful assertion from the `assert` methods do not mark the test or the `it` block as passed, hence the test result is 0 test passed and would not be counted as passed.

The same happens regardless of whether the assertions are made inside any `describe`/`it` blocks.

Overall it seems like `assert` is only used internally? Then I don't see why it should be available in the open.

**Comment by kazk** [comment]
Node 6/8 does `require('assert')` (from Node). I don't know why, but it's from this old runner.

https://github.com/Codewars/codewars-runner-cli/blob/aeb3c44d46f72d732d3d776d5c299b3ac2f6f6be/lib/runners/javascript/index.js#L154

I'm not sure why threre's a difference between 6 and 8 though. Maybe something changed in Node.

> But both of them are broken actually, because a successful assertion from the assert methods do not mark the test or the `it` block as passed, hence the test result is 0 test passed and would not be counted as passed.

This is because `assert` doesn't output `<PASSED::>` that `cw-2` requires.

**Comment by kazk** [comment]
Closing because newer `assert` is no longer included when using newer Node versions.
