### ISSUE TITLE
[Coq] Deprecate the post-processor on runner output

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars-runner-cli#753]
Thanks to [coq_codewars](https://github.com/Codewars/coq_codewars) contributed by @monadius, we no longer need to rely on `Print Assumptions` for testing; therefore, the post-processor should be deprecated (I also suspect that it might have something to do with #752 ). Obviously this is a breaking change and will break all Coq Kata authored before `coq_codewars` was available but considering that Coq tests are easy to write/fix and there are currently just over 50 Coq Kata in total (many of which are still in Beta), it's probably better to perform the breaking changes sooner rather than later.

**Comment by DonaldKellett** [comment]
On a completely unrelated note, any intentions on officially moving Coq support on CW out of the Beta phase? :wink:

**Comment by Bubbler-4** [comment]
Actually we'd need a new beta phase for the new testing (mini-)framework before graduating; we might encounter some possible improvements and/or bug fixes.

Also, the post-processor does more than just handling `Print Assumptions`; it also encapsulates logs into log windows and error messages into error windows (though not perfect in that aspect either). I'm not sure whether getting rid of the post-processor entirely would be perfectly safe.

**Comment by kazk** [comment]
We can remove the part that handles "Closed under global context" and "Axioms" after updating the existing kata, but most of it is still necessary. I wasn't planning to remove it because it didn't look like it's getting in the way, but I can do it if it is and after the existing kata is updated.

The post processor doesn't have anything to do with the nested describe issue.

I should move some languages out of beta, but I don't think Coq is ready yet.

**Comment by DonaldKellett** [comment]
Closing since the post-processor does not interfere with [coq_codewars](https://github.com/Codewars/coq_codewars/).
