### ISSUE TITLE
JS line number is now offset from the actual line number

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#779]
I recently discovered that JS line numbers does not match the actual line number in user code anymore (AFAIK it used to be correct), just like what PHP has been doing all the time.

Example:

User code:
```
function add(a, b) {
  return a.join();
}
```

Test fixture:
```
describe("Solution", function() {
  it("should test for something", function() {
    Test.assertEquals(add(1,1), 2);
  });
});
```

Now Node 8 gives

![image](https://user-images.githubusercontent.com/14909989/72696726-5c5e0000-3b78-11ea-81ca-76ba40b755e3.png)

and Node 10 gives

![image](https://user-images.githubusercontent.com/14909989/72696744-6c75df80-3b78-11ea-903a-efa8f627f5c3.png)

The offset seems to be `1 + number of lines in Preloaded`, which the user cannot see anymore, so it's very difficult to determine the real line number of user code.

**Comment by kazk** [comment]
> I recently discovered that JS line numbers does not match the actual line number in user code anymore (AFAIK it used to be correct),

No, it was never correct. The files are wrapped and concatenated:

https://github.com/Codewars/codewars-runner-cli/blob/aeb3c44d46f72d732d3d776d5c299b3ac2f6f6be/lib/runners/javascript/index.js#L152-L165

Node v6/8 looks mostly the same as above.
Node v10 has less wrapping because it uses Mocha under the hood, but that's the only difference.
