### ISSUE TITLE
Add NodeJS 12

### ISSUE THREAD

**Issue by victorperin** [codewars/codewars-runner-cli#816]
Please complete the following information:

- Name: Update NodeJS environment to recent versions
- Version: 12.x and 14.x
- Some new JS features:
    - Object.fromEntries
    - Array.flatMap
    - String.matchAll
    - Promise.allSettled
    - Instance class fields

**Comment by kazk** [comment]
Node 12 is now supported, but only 256 kata have it enabled at the moment.

I'm planning to write some script to automatically migrate incompatible tests sometime soon and that should increase the number significantly.

In the meantime, kata can be manually upgraded by one of the following two ways:

- Rewrite assertions to use `chai` instead of the functions from the deprecated custom framework (preferred)
- Add `const Test = require("@codewars/test-compat");` that [provides aliases](https://github.com/codewars/javascript-test-compat) (easier)
